### ISSUE TITLE
Interval ordering and stage merging do not respect data dependencies

### ISSUE THREAD

**Issue by eddie-c-davis** [GridTools/gt4py#184] opened 2020-09-17 22:05 UTC
Since the merging of [PR #169](https://github.com/GridTools/gt4py/pull/169) into master, stencils in the FV3 dynamical core (`fv3core`) that previously validated no longer produce correct data. The following stencil snippet demonstrates the problem:
```python
@gtscript.stencil()
def reorder_issue(dm: gtscript.Field[float]):
    with computation(FORWARD):
        with interval(0, -2):
            bb = 2.0 * (1.0 + dm)
        with interval(0, 1):
            bet = bb
        with interval(1, None):
            bet = bet[0, 0, -1]
```
After the intervals are sorted, the following code would be generated:
```python
for K in range(0, 1):
    bet = bb
for K in range(0, domain[2] - 2):
     bb = 2.0 * (1.0 + dm)
for K in range(1, domain[2]):
    bet = bet[0, 0, -1]
```
This results in the temporary field, `bb`, being written to the `bet` field in the interval (0, 1) before `bb` is computed on interval (0, domain[2] - 2). If one introduces a new computation block to enforce separation,
```python
@gtscript.stencil()
def reorder_issue(dm: gtscript.Field[float]):
    with computation(FORWARD):
        with interval(0, -2):
            bb = 2.0 * (1.0 + dm)
    with computation(FORWARD):
        with interval(0, 1):
            bet = bb
        with interval(1, None):
            bet = bet[0, 0, -1]
```
the multi-stages are merged and the same output code is generated. Only changing the iteration order of the first multi-stage resolves the problem,
```python
@gtscript.stencil()
def reorder_issue(dm: gtscript.Field[float]):
    with computation(PARALLEL):
        with interval(0, -2):
            bb = 2.0 * (1.0 + dm)
    with computation(FORWARD):
        with interval(0, 1):
            bet = bb
        with interval(1, None):
            bet = bet[0, 0, -1]
```
by generating the following:
```python
parfor K in range(0, 1):
    bet = bb
for K in range(0, domain[2] - 2):
     bb = 2.0 * (1.0 + dm)
for K in range(1, domain[2]):
    bet = bet[0, 0, -1]
```

**Comment by twicki** [comment] 2020-09-18 00:40
my opinion here is that we should generate an error if we have overlapping intervals in the same `computation` since this creates behaviour that is not explainable (even though it technically is unambiguous) and therefore is very counter-intuitive.

The solution we should push the developer to use is actually the third code that @eddie-c-davis presents since it is clearly defined what the order should be:
```python
@gtscript.stencil()
def reorder_issue(dm: gtscript.Field[float]):
    with computation(FORWARD):
        with interval(0, -2):
            bb = 2.0 * (1.0 + dm)
    with computation(FORWARD):
        with interval(0, 1):
            bet = bb
        with interval(1, None):
            bet = bet[0, 0, -1]
```

The problem is that this is broken with fusion which should be fixed.

**Comment by egparedes** [comment] 2020-09-18 12:08
I agree with @twicki that there are two different issues here:
1. Overlapping intervals in the same computation cannot be not allowed at all.
2. Fusion of multi-stages is broken in this case

I have created a new issue #187 to fix the first point and thus we could focus on fixing the broken fusion of multi-stages in this issue.

**Comment by eddie-c-davis** [comment] 2020-09-21 22:52
Providing another example, in case it is useful.
```python
@gtscript.stencil()
def reorder_issue(dm: Field[float], aa: Field[float], pp: Field[float], dt: float):
    with computation(FORWARD):
        with interval(0, 1):
            bet = dm - aa[0, 0, 1]
        with interval(1, None):
            tmp = bet[0, 0, -1]
            bet = tmp
    with computation(FORWARD):
        with interval(1, -2):
            gam = aa / bet[0, 0, -1]
            bet = dm - (aa + aa[0, 0, 1] + aa * gam)
```
In this case, the `gam = aa / bet[0, 0, -1]` statement is executed before the `bet = tmp` statement that should run before `bet[0, 0, -1]` is read.
```python
for k in range(0, 1):
    bet = dm - aa[i, j, k+1]
for k in range(1, domain[2] - 2):
    gam = aa / bet[i, j, k-1]
for k in range(1, domain[2]):
    tmp = bet[i, j, k-1]
    bet = tmp
for k in range(1, domain[2] - 2):
    bet = dm - (aa + aa[i, j, k+1] + aa * gam)
```

**Closed** 2020-12-15 12:57 UTC
Labels: module: analysis, priority: high, triage: bug
