### ISSUE TITLE
Access outside of domain in k dimension fails in dace

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#461] opened 2021-07-14 10:04 UTC
The following stencil currently fails with all gtc based backends:

```python
@stencil(backend=backend, **backend_opts)
def _nabla_z(
    pp : gtscript.Field[dtype],
    pz : gtscript.Field[dtype],
    dz : dtype
    ):

    with computation(PARALLEL), interval(...):
        dz2i = 0.5 / dz
        pz[0,0,0] = (pp[0,0,1] - pp[0,0,-1]) * dz2i
```
Error message:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/tille/Development/MPDATA_GT4PY/src/mpdata/model/config.py", line 13, in <module>
    from mpdata.geometry.curvilinear import Metric
  File "/home/tille/Development/MPDATA_GT4PY/src/mpdata/geometry/curvilinear.py", line 12, in <module>
    from mpdata.operators.nabla import Nabla
  File "/home/tille/Development/MPDATA_GT4PY/src/mpdata/operators/nabla.py", line 87, in <module>
    def _nabla_z(
  File "/home/tille/Development/MPDATA_GT4PY/src/mpdata/utils/stencil.py", line 113, in _decorator
    stencil_obj = gt.gtscript.stencil(backend, definition, **kwargs)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/gtscript.py", line 269, in stencil
    return _decorator(definition)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/gtscript.py", line 257, in _decorator
    out = gt_loader.gtscript_loader(
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/loader.py", line 72, in gtscript_loader
    stencil_class = load_stencil("gtscript", backend, definition_func, externals, build_options)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/loader.py", line 58, in load_stencil
    return builder.build()
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/stencil_builder.py", line 72, in build
    stencil_class = self.backend.generate()
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gtc_backend/gtcpp/backend.py", line 152, in generate
    pyext_module_name, pyext_file_path = self.generate_extension()
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gtc_backend/gtcpp/backend.py", line 177, in generate_extension
    return super()._generate_extension(uses_cuda=False)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gtc_backend/gtcpp/backend.py", line 139, in _generate_extension
    return self.make_extension(gt_version=2, ir=self.builder.definition_ir, uses_cuda=uses_cuda)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gt_backends.py", line 633, in make_extension
    gt_pyext_sources: Dict[str, Any] = self.make_extension_sources(ir=ir)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gt_backends.py", line 667, in make_extension_sources
    gt_pyext_sources = gt_pyext_generator(ir)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gt4py/backend/gtc_backend/gtcpp/backend.py", line 57, in __call__
    oir = OirPipeline(gtir_to_oir.GTIRToOIR().visit(gtir)).full(
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/passes/oir_pipeline.py", line 101, in full
    return self._get_cached(pipeline) or self._set_cached(pipeline, self.apply(pipeline))
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/passes/oir_pipeline.py", line 80, in apply
    result = step(result)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/passes/oir_dace_optimizations/horizontal_execution_merging.py", line 262, in graph_merge_horizontal_executions
    return optimize_horizontal_executions(node, GraphMerging)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/passes/oir_dace_optimizations/api.py", line 28, in optimize_horizontal_executions
    sdfg = OirSDFGBuilder().visit(stencil)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/eve/visitors.py", line 121, in visit
    return visitor(node, **kwargs)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/dace/oir_to_dace.py", line 632, in visit_Stencil
    return StencilOirSDFGBuilder.build(node.name, node, library_nodes)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/gtc/dace/oir_to_dace.py", line 381, in build
    res.validate()
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/dace/sdfg/sdfg.py", line 1933, in validate
    validate_sdfg(self)
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/dace/sdfg/validation.py", line 110, in validate_sdfg
    validate_state(start_state, sdfg.node_id(start_state), sdfg,
  File "/home/tille/Development/MPDATA_GT4PY/venv/lib/python3.9/site-packages/dace/sdfg/validation.py", line 430, in validate_state
    raise InvalidSDFGEdgeError(
dace.sdfg.validation.InvalidSDFGEdgeError: Memlet subset negative out-of-bounds (at state _nabla_z_state, edge pp[0:__I, 0:__J, -1:__K + 1] (pp:None -> VerticalLoop_139625918520816:IN_pp))
python-BaseException

```

**Comment by gronerl** [comment] 2021-07-15 22:05
duplicate of #437

**Closed** 2021-08-04 08:07 UTC
Labels: triage: bug
