### ISSUE TITLE
Cannot import GT4Py

### ISSUE THREAD

**Issue by stubbiali** [GridTools/gt4py#151] opened 2020-08-18 13:39 UTC
When importing GT4Py with Dawn installed, this [line](https://github.com/GridTools/gt4py/blob/338f7f7ddaecce6afb26ec449bdb4a267063b016/src/gt4py/backend/dawn_backends.py#L254) fails with ﻿`AttributeError: module 'dawn4py.serialization.SIR' has no attribute 'VerticalRegionStmt'`.

**Comment by mbianco** [comment] 2020-08-19 06:19
This happens even if do not use Dawn? Just if it is installed?

**Comment by stubbiali** [comment] 2020-08-19 07:56
Yes. If `dawn4py` is available the module `gt4py.backend.dawn_backends` gets imported and leads to this error.

**Comment by egparedes** [comment] 2020-08-19 08:53
When loading gt4py, if dawn4py is available it will be imported, so it's normal to get an error if something is wrong in the dawn4py bindings. I think this error appears because the interface of the dawn4py bindings have been changed but the dawn4py backend or the dependency version in gt4py has not been updated consequently. It is probably easy to fix by someone from Vulcan verifying that:

- there is a proper tag in the dawn repo for the current stable version of dawn4py bindings
- the dawn backends in gt4py are using the latest dawn4py interface
- the required version of dawn4py dependency in setup.cfg matches the current stable version of dawn4py

**Comment by DropD** [comment] 2020-09-02 08:03
As of today I can not reproduce this.

```bash
$ pip install -e gt4py[dawn]
$ python -c "import gt4py"
```

Does not give any errors.

We can not support all possible versions of `dawn4py` and installing it separately will always be hit or miss.
So if nobody comes up with a reason to keep this issue open I will close it soon.

**Comment by mbianco** [comment] 2020-09-02 08:16
What is the solution for Stefano, then? If Dawn4py is installed, what should he do?

**Comment by stubbiali** [comment] 2020-09-02 08:16
Yes, it works fine on my side too now. Please go ahead and close it.

**Closed** 2020-09-02 08:53 UTC
Labels: triage: bug
